#!/bin/sh

# Copyright 2006 Helsinki Institute for Information Technology

# This file is a part of Fuego middleware.  Fuego middleware is free
# software; you can redistribute it and/or modify it under the terms
# of the MIT license, included as the file MIT-LICENSE in the Fuego
# middleware source distribution.  If you did not receive the MIT
# license with the distribution, write to the Fuego Core project at
# fuego-core-users@hoslab.cs.helsinki.fi.

cd message/data || (echo "FAIL: wrong directory"; exit 1)
COA=../../=build/bin/coa

if [ ! -x $COA ] ; then
    echo "FAIL: no COA present"
    exit 1
fi

value=0

for sfx in raw print defs; do
    loop=0
    for i in *.rnc; do
	base=`basename $i .rnc`
	file=`tempfile`
	$COA $sfx $i >$file
	if ! cmp ../output/$base.$sfx $file ; then
	    echo "FAIL: $sfx $i"
	    value=1
	    loop=1
	fi
	rm -f $file
    done
    if [ $loop -eq 0 ]; then
	echo "PASS: $sfx"
    fi
done

exit $value
